spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.796fcbb8e07410be
            clientSecret: d9c199b9231190edaa6e90f5a571c28730fe7ffb
          google:
            clientId: 700086744673-keplb3hc6ere9uiqddg4aleho4i08g37.apps.googleusercontent.com
            clientSecret: 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




#  github:
#    clientId: Iv1.731596c579d3b990
#    clientSecret: 1a16900f622b3b74d6d2e1efa40c53a63ad8705d
#    google:
#      clientId: 700086744673-keplb3hc6ere9uiqddg4aleho4i08g37.apps.googleusercontent.com
#      clientSecret: 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